<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SAMPATH" failures="0" tests="8" name="com.RestAssuredAutomation.TestCases.TC005_Delete_Employee_Record" time="2.263" errors="1" timestamp="06 Feb 2022 10:35:25 GMT" skipped="7">
  <testcase classname="com.RestAssuredAutomation.TestCases.TC005_Delete_Employee_Record" name="checkResponseTime" time="0.000">
    <skipped/>
  </testcase> <!-- checkResponseTime -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC005_Delete_Employee_Record" name="DeleteEmpRecord" time="2.263">
    <error message="Failed to parse the JSON document" type="io.restassured.path.json.exception.JsonPathException">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:986)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:951)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1031)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at com.RestAssuredAutomation.TestCases.TC005_Delete_Employee_Record.DeleteEmpRecord(TC005_Delete_Employee_Record.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:87)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:949)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:984)
... 30 more
]]>
    </error>
  </testcase> <!-- DeleteEmpRecord -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC005_Delete_Employee_Record" name="checkResponseBody" time="0.000">
    <skipped/>
  </testcase> <!-- checkResponseBody -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC005_Delete_Employee_Record" name="checkStatusCode" time="0.000">
    <skipped/>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC005_Delete_Employee_Record" name="checkServerType" time="0.000">
    <skipped/>
  </testcase> <!-- checkServerType -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC005_Delete_Employee_Record" name="checkContentType" time="0.000">
    <skipped/>
  </testcase> <!-- checkContentType -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC005_Delete_Employee_Record" name="checkStatusLine" time="0.000">
    <skipped/>
  </testcase> <!-- checkStatusLine -->
  <testcase classname="com.RestAssuredAutomation.TestCases.TC005_Delete_Employee_Record" name="checkContentEncoding" time="0.000">
    <skipped/>
  </testcase> <!-- checkContentEncoding -->
</testsuite> <!-- com.RestAssuredAutomation.TestCases.TC005_Delete_Employee_Record -->
